name: ranger
version: 0.1.2
author: William DeVore
description: A game engine written in Dart and slightly modeled after Cocos2d-js.
homepage: https://github.com/wdevore/Ranger-Dart
documentation: https://github.com/wdevore/Ranger-Dart
dependencies:
  browser: any
  color_slider_control:
    git: git://github.com/wdevore/color_slider_control.git
  event_bus: any
  gradient_colorstops_control:
    git: git://github.com/wdevore/gradient_colorstops_control.git
  lawndart: any
  tweenengine: any
  vector_math: any
