name: ranger
version: 0.9.88
author: William DeVore
description: A game engine written in Dart and slightly modeled after Cocos2d-js. Its companion project is Ranger-Sack.
homepage: https://github.com/wdevore/Ranger-Dart
documentation: https://github.com/wdevore/Ranger-Dart
dependencies:
  browser: any
  event_bus: any
  tweenengine: any
  vector_math: any
